version: '3.9'

services:
    library-service:
        image: library-service:1.1.0
        build:
            context: ./library-service
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
        depends_on:
            - library-postgres
            - rabbitmq
        environment:
            SERVER_PORT: 8082
            SPRING_DATASOURCE_URL: jdbc:postgresql://library-postgres:5432/library_db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres

    crud-service:
        image: crud-service:1.1.0
        build:
            context: ./crud-service
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        depends_on:
            - crud-postgres
            - rabbitmq
        environment:
            SERVER_PORT: 8081
            SPRING_DATASOURCE_URL: jdbc:postgresql://crud-postgres:5432/crud_db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres

    auth-service:
        image: auth-service:1.1.0
        build:
            context: ./auth-service
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        depends_on:
            - auth-postgres
        environment:
            SERVER_PORT: 8083
            SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_db
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres

    crud-postgres:
        image: postgres:15-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: crud_db

    library-postgres:
        image: postgres:15-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: library_db

    auth-postgres:
        image: postgres:15-alpine
        ports:
            - "5434:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: auth_db

    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

volumes:
    rabbitmq_data:

